### ISSUE TITLE
LoadQRAW hangs forever if variables do not exist in .qraw

### ISSUE THREAD

**Issue by driftregion** [Qorvo/PyQSPICE#3]
Hello, thank you for PyQSPICE. 

 `LoadQRAW` hangs indefinitely if I pass an nonexistent variable name to it.

Expected behavior: Throw an exception such as KeyError.
Version: PyQSPICE-2024.4.11

This can be reproduced by changing step 6 of the QuickStart  https://github.com/Qorvo/PyQSPICE/blob/main/QuickStart.ipynb as follows from

```python
df = run.LoadQRAW(["Id(J1)"])
```

to

```python
df = run.LoadQRAW(["Id(J11)"])
```

**Comment by MasashiNogawa** [comment]
@driftregion 

I'm so sorry, I failed to reply to you in time.

***

This is a little bit tough challenge to distinguish below 2 cases.
1. You are reading very, very big .qraw file and it just takes long time to finish loading.
2. You specified a wrong variable.

So to support "1.", any "time out" (timer) setting is not an option.

For your concern of "2.", I wrote a method "parseCir()" in the PyQSPICE but I stopped there in the half way of writing this "parseCir()"...because I have no way to know user custom sub circuit details.

***

Please let me close this for now until someone gets a clever idea to distinguish "1" and "2" efficiently.
